package handlers

import (
	"context"
	"fmt"
	"os"
	"strconv"
	"time"

	"github.com/MishraShardendu22/github-backup/backend/db"
	"github.com/gofiber/fiber/v2"
	"gopkg.in/gomail.v2"
)

type ReportRequest struct {
	ReportType string `json:"report_type"` // latest, failure, manual
}

func SendReport(c *fiber.Ctx) error {
	var req ReportRequest
	if err := c.BodyParser(&req); err != nil {
		req.ReportType = "latest"
	}

	smtpHost := os.Getenv("SMTP_HOST")
	smtpPortStr := os.Getenv("SMTP_PORT")
	smtpUser := os.Getenv("SMTP_USERNAME")
	smtpPass := os.Getenv("SMTP_PASSWORD")
	smtpFrom := os.Getenv("SMTP_FROM")
	smtpTo := os.Getenv("SMTP_TO")

	if smtpHost == "" || smtpUser == "" || smtpPass == "" {
		return c.Status(500).JSON(fiber.Map{"error": "SMTP not configured"})
	}

	smtpPort, _ := strconv.Atoi(smtpPortStr)
	if smtpPort == 0 {
		smtpPort = 587
	}

	subject, body := buildReport(req.ReportType)

	m := gomail.NewMessage()
	m.SetHeader("From", smtpFrom)
	m.SetHeader("To", smtpTo)
	m.SetHeader("Subject", subject)
	m.SetBody("text/html", body)

	d := gomail.NewDialer(smtpHost, smtpPort, smtpUser, smtpPass)

	if err := d.DialAndSend(m); err != nil {
		// Log failure
		db.Pool.Exec(context.Background(),
			`INSERT INTO report_history (report_type, recipients, subject, status, error_message) VALUES ($1, $2, $3, 'failed', $4)`,
			req.ReportType, smtpTo, subject, err.Error())
		return c.Status(500).JSON(fiber.Map{"error": "failed to send email: " + err.Error()})
	}

	// Log success
	db.Pool.Exec(context.Background(),
		`INSERT INTO report_history (report_type, recipients, subject, status) VALUES ($1, $2, $3, 'sent')`,
		req.ReportType, smtpTo, subject)

	return c.JSON(fiber.Map{"sent": true, "subject": subject, "to": smtpTo})
}

func GetReportHistory(c *fiber.Ctx) error {
	rows, err := db.Pool.Query(context.Background(),
		`SELECT id, report_type, recipients, subject, status, error_message, sent_at
		 FROM report_history ORDER BY sent_at DESC LIMIT 50`)
	if err != nil {
		return c.Status(500).JSON(fiber.Map{"error": err.Error()})
	}
	defer rows.Close()

	type Report struct {
		ID           int       `json:"id"`
		ReportType   string    `json:"report_type"`
		Recipients   string    `json:"recipients"`
		Subject      string    `json:"subject"`
		Status       string    `json:"status"`
		ErrorMessage string    `json:"error_message"`
		SentAt       time.Time `json:"sent_at"`
	}

	var reports []Report
	for rows.Next() {
		var r Report
		if err := rows.Scan(&r.ID, &r.ReportType, &r.Recipients, &r.Subject, &r.Status, &r.ErrorMessage, &r.SentAt); err != nil {
			continue
		}
		reports = append(reports, r)
	}

	if reports == nil {
		reports = []Report{}
	}
	return c.JSON(reports)
}

func buildReport(reportType string) (string, string) {
	ctx := context.Background()

	switch reportType {
	case "failure":
		return buildFailureReport(ctx)
	default:
		return buildLatestReport(ctx)
	}
}

func buildLatestReport(ctx context.Context) (string, string) {
	var status string
	var startedAt time.Time
	var totalRepos, successful, failed, skipped int
	var durationMs int64

	err := db.Pool.QueryRow(ctx,
		`SELECT status, started_at, total_repos, successful, failed, skipped, duration_ms
		 FROM backup_runs ORDER BY started_at DESC LIMIT 1`).Scan(
		&status, &startedAt, &totalRepos, &successful, &failed, &skipped, &durationMs)

	if err != nil {
		return "Backup Report", "<h2>No backup data available</h2>"
	}

	subject := fmt.Sprintf("Backup Report - %s - %s", status, startedAt.Format("2006-01-02"))

	body := fmt.Sprintf(`
<html><body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
<h2 style="color: %s;">Backup %s</h2>
<table style="width:100%%; border-collapse: collapse;">
<tr><td style="padding:8px; border:1px solid #ddd;"><strong>Started</strong></td><td style="padding:8px; border:1px solid #ddd;">%s</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><strong>Duration</strong></td><td style="padding:8px; border:1px solid #ddd;">%s</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><strong>Total Repos</strong></td><td style="padding:8px; border:1px solid #ddd;">%d</td></tr>
<tr style="background:#e8f5e9;"><td style="padding:8px; border:1px solid #ddd;"><strong>Successful</strong></td><td style="padding:8px; border:1px solid #ddd;">%d</td></tr>
<tr style="background:#ffebee;"><td style="padding:8px; border:1px solid #ddd;"><strong>Failed</strong></td><td style="padding:8px; border:1px solid #ddd;">%d</td></tr>
<tr><td style="padding:8px; border:1px solid #ddd;"><strong>Skipped</strong></td><td style="padding:8px; border:1px solid #ddd;">%d</td></tr>
</table>
<p style="color:#888; font-size:12px; margin-top:20px;">Generated by GitHub Backup Monitor</p>
</body></html>`,
		statusColor(status), status,
		startedAt.Format("2006-01-02 15:04:05 MST"),
		formatDuration(durationMs),
		totalRepos, successful, failed, skipped)

	return subject, body
}

func buildFailureReport(ctx context.Context) (string, string) {
	rows, err := db.Pool.Query(ctx,
		`SELECT repo_full_name, error_message, created_at
		 FROM backup_results WHERE status = 'failed'
		 ORDER BY created_at DESC LIMIT 20`)
	if err != nil {
		return "Failure Alert", "<h2>Could not fetch failure data</h2>"
	}
	defer rows.Close()

	body := `<html><body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
<h2 style="color: #d32f2f;">⚠️ Backup Failure Alert</h2>
<table style="width:100%; border-collapse: collapse;">
<tr style="background:#f5f5f5;"><th style="padding:8px; border:1px solid #ddd; text-align:left;">Repository</th><th style="padding:8px; border:1px solid #ddd; text-align:left;">Error</th><th style="padding:8px; border:1px solid #ddd; text-align:left;">Time</th></tr>`

	count := 0
	for rows.Next() {
		var repo, errMsg string
		var t time.Time
		rows.Scan(&repo, &errMsg, &t)
		body += fmt.Sprintf(`<tr><td style="padding:8px; border:1px solid #ddd;">%s</td><td style="padding:8px; border:1px solid #ddd;">%s</td><td style="padding:8px; border:1px solid #ddd;">%s</td></tr>`,
			repo, errMsg, t.Format("01-02 15:04"))
		count++
	}

	if count == 0 {
		body += `<tr><td colspan="3" style="padding:8px; text-align:center;">No failures found 🎉</td></tr>`
	}

	body += `</table><p style="color:#888; font-size:12px; margin-top:20px;">Generated by GitHub Backup Monitor</p></body></html>`

	return fmt.Sprintf("Backup Failure Alert - %d failures", count), body
}

func statusColor(status string) string {
	if status == "completed" {
		return "#2e7d32"
	}
	return "#d32f2f"
}

func formatDuration(ms int64) string {
	d := time.Duration(ms) * time.Millisecond
	if d < time.Minute {
		return fmt.Sprintf("%.1fs", d.Seconds())
	}
	return fmt.Sprintf("%.1fm", d.Minutes())
}
