DROP TABLE IF EXISTS backup_run_fixes CASCADE;
DROP TABLE IF EXISTS backup_fixes CASCADE;
DROP TABLE IF EXISTS analytics_snapshots CASCADE;
DROP TABLE IF EXISTS execution_logs CASCADE;
DROP TABLE IF EXISTS backup_results CASCADE;
DROP TABLE IF EXISTS backup_runs CASCADE;
